# This is a countries list.
INSERT INTO countries (code, name) VALUES('AF', 'Afganistán');
INSERT INTO countries (code, name) VALUES('AX', 'Islas Gland');
INSERT INTO countries (code, name) VALUES('AL', 'Albania');
INSERT INTO countries (code, name) VALUES('DE', 'Alemania');
INSERT INTO countries (code, name) VALUES('AD', 'Andorra');
INSERT INTO countries (code, name) VALUES('AO', 'Angola');
INSERT INTO countries (code, name) VALUES('AI', 'Anguilla');
INSERT INTO countries (code, name) VALUES('AQ', 'Antártida');
INSERT INTO countries (code, name) VALUES('AG', 'Antigua y Barbuda');
INSERT INTO countries (code, name) VALUES('AN', 'Antillas Holandesas');
INSERT INTO countries (code, name) VALUES('SA', 'Arabia Saudí');
INSERT INTO countries (code, name) VALUES('DZ', 'Argelia');
INSERT INTO countries (code, name) VALUES('AR', 'Argentina');
INSERT INTO countries (code, name) VALUES('AM', 'Armenia');
INSERT INTO countries (code, name) VALUES('AW', 'Aruba');
INSERT INTO countries (code, name) VALUES('AU', 'Australia');
INSERT INTO countries (code, name) VALUES('AT', 'Austria');
INSERT INTO countries (code, name) VALUES('AZ', 'Azerbaiyán');
INSERT INTO countries (code, name) VALUES('BS', 'Bahamas');
INSERT INTO countries (code, name) VALUES('BH', 'Bahréin');
INSERT INTO countries (code, name) VALUES('BD', 'Bangladesh');
INSERT INTO countries (code, name) VALUES('BB', 'Barbados');
INSERT INTO countries (code, name) VALUES('BY', 'Bielorrusia');
INSERT INTO countries (code, name) VALUES('BE', 'Bélgica');
INSERT INTO countries (code, name) VALUES('BZ', 'Belice');
INSERT INTO countries (code, name) VALUES('BJ', 'Benin');
INSERT INTO countries (code, name) VALUES('BM', 'Bermudas');
INSERT INTO countries (code, name) VALUES('BT', 'Bhután');
INSERT INTO countries (code, name) VALUES('BO', 'Bolivia');
INSERT INTO countries (code, name) VALUES('BA', 'Bosnia y Herzegovina');
INSERT INTO countries (code, name) VALUES('BW', 'Botsuana');
INSERT INTO countries (code, name) VALUES('BV', 'Isla Bouvet');
INSERT INTO countries (code, name) VALUES('BR', 'Brasil');
INSERT INTO countries (code, name) VALUES('BN', 'Brunéi');
INSERT INTO countries (code, name) VALUES('BG', 'Bulgaria');
INSERT INTO countries (code, name) VALUES('BF', 'Burkina Faso');
INSERT INTO countries (code, name) VALUES('BI', 'Burundi');
INSERT INTO countries (code, name) VALUES('CV', 'Cabo Verde');
INSERT INTO countries (code, name) VALUES('KY', 'Islas Caimán');
INSERT INTO countries (code, name) VALUES('KH', 'Camboya');
INSERT INTO countries (code, name) VALUES('CM', 'Camerún');
INSERT INTO countries (code, name) VALUES('CA', 'Canadá');
INSERT INTO countries (code, name) VALUES('CF', 'República Centroafricana');
INSERT INTO countries (code, name) VALUES('TD', 'Chad');
INSERT INTO countries (code, name) VALUES('CZ', 'República Checa');
INSERT INTO countries (code, name) VALUES('CL', 'Chile');
INSERT INTO countries (code, name) VALUES('CN', 'China');
INSERT INTO countries (code, name) VALUES('CY', 'Chipre');
INSERT INTO countries (code, name) VALUES('CX', 'Isla de Navidad');
INSERT INTO countries (code, name) VALUES('VA', 'Ciudad del Vaticano');
INSERT INTO countries (code, name) VALUES('CC', 'Islas Cocos');
INSERT INTO countries (code, name) VALUES('CO', 'Colombia');
INSERT INTO countries (code, name) VALUES('KM', 'Comoras');
INSERT INTO countries (code, name) VALUES('CD', 'República Democrática del Congo');
INSERT INTO countries (code, name) VALUES('CG', 'Congo');
INSERT INTO countries (code, name) VALUES('CK', 'Islas Cook');
INSERT INTO countries (code, name) VALUES('KP', 'Corea del Norte');
INSERT INTO countries (code, name) VALUES('KR', 'Corea del Sur');
INSERT INTO countries (code, name) VALUES('CI', 'Costa de Marfil');
INSERT INTO countries (code, name) VALUES('CR', 'Costa Rica');
INSERT INTO countries (code, name) VALUES('HR', 'Croacia');
INSERT INTO countries (code, name) VALUES('CU', 'Cuba');
INSERT INTO countries (code, name) VALUES('DK', 'Dinamarca');
INSERT INTO countries (code, name) VALUES('DM', 'Dominica');
INSERT INTO countries (code, name) VALUES('DO', 'República Dominicana');
INSERT INTO countries (code, name) VALUES('EC', 'Ecuador');
INSERT INTO countries (code, name) VALUES('EG', 'Egipto');
INSERT INTO countries (code, name) VALUES('SV', 'El Salvador');
INSERT INTO countries (code, name) VALUES('AE', 'Emiratos Árabes Unidos');
INSERT INTO countries (code, name) VALUES('ER', 'Eritrea');
INSERT INTO countries (code, name) VALUES('SK', 'Eslovaquia');
INSERT INTO countries (code, name) VALUES('SI', 'Eslovenia');
INSERT INTO countries (code, name) VALUES('ES', 'España');
INSERT INTO countries (code, name) VALUES('UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO countries (code, name) VALUES('US', 'Estados Unidos');
INSERT INTO countries (code, name) VALUES('EE', 'Estonia');
INSERT INTO countries (code, name) VALUES('ET', 'Etiopía');
INSERT INTO countries (code, name) VALUES('FO', 'Islas Feroe');
INSERT INTO countries (code, name) VALUES('PH', 'Filipinas');
INSERT INTO countries (code, name) VALUES('FI', 'Finlandia');
INSERT INTO countries (code, name) VALUES('FJ', 'Fiyi');
INSERT INTO countries (code, name) VALUES('FR', 'Francia');
INSERT INTO countries (code, name) VALUES('GA', 'Gabón');
INSERT INTO countries (code, name) VALUES('GM', 'Gambia');
INSERT INTO countries (code, name) VALUES('GE', 'Georgia');
INSERT INTO countries (code, name) VALUES('GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO countries (code, name) VALUES('GH', 'Ghana');
INSERT INTO countries (code, name) VALUES('GI', 'Gibraltar');
INSERT INTO countries (code, name) VALUES('GD', 'Granada');
INSERT INTO countries (code, name) VALUES('GR', 'Grecia');
INSERT INTO countries (code, name) VALUES('GL', 'Groenlandia');
INSERT INTO countries (code, name) VALUES('GP', 'Guadalupe');
INSERT INTO countries (code, name) VALUES('GU', 'Guam');
INSERT INTO countries (code, name) VALUES('GT', 'Guatemala');
INSERT INTO countries (code, name) VALUES('GF', 'Guayana Francesa');
INSERT INTO countries (code, name) VALUES('GN', 'Guinea');
INSERT INTO countries (code, name) VALUES('GQ', 'Guinea Ecuatorial');
INSERT INTO countries (code, name) VALUES('GW', 'Guinea-Bissau');
INSERT INTO countries (code, name) VALUES('GY', 'Guyana');
INSERT INTO countries (code, name) VALUES('HT', 'Haití');
INSERT INTO countries (code, name) VALUES('HM', 'Islas Heard y McDonald');
INSERT INTO countries (code, name) VALUES('HN', 'Honduras');
INSERT INTO countries (code, name) VALUES('HK', 'Hong Kong');
INSERT INTO countries (code, name) VALUES('HU', 'Hungría');
INSERT INTO countries (code, name) VALUES('IN', 'India');
INSERT INTO countries (code, name) VALUES('ID', 'Indonesia');
INSERT INTO countries (code, name) VALUES('IR', 'Irán');
INSERT INTO countries (code, name) VALUES('IQ', 'Iraq');
INSERT INTO countries (code, name) VALUES('IE', 'Irlanda');
INSERT INTO countries (code, name) VALUES('IS', 'Islandia');
INSERT INTO countries (code, name) VALUES('IL', 'Israel');
INSERT INTO countries (code, name) VALUES('IT', 'Italia');
INSERT INTO countries (code, name) VALUES('JM', 'Jamaica');
INSERT INTO countries (code, name) VALUES('JP', 'Japón');
INSERT INTO countries (code, name) VALUES('JO', 'Jordania');
INSERT INTO countries (code, name) VALUES('KZ', 'Kazajstán');
INSERT INTO countries (code, name) VALUES('KE', 'Kenia');
INSERT INTO countries (code, name) VALUES('KG', 'Kirguistán');
INSERT INTO countries (code, name) VALUES('KI', 'Kiribati');
INSERT INTO countries (code, name) VALUES('KW', 'Kuwait');
INSERT INTO countries (code, name) VALUES('LA', 'Laos');
INSERT INTO countries (code, name) VALUES('LS', 'Lesotho');
INSERT INTO countries (code, name) VALUES('LV', 'Letonia');
INSERT INTO countries (code, name) VALUES('LB', 'Líbano');
INSERT INTO countries (code, name) VALUES('LR', 'Liberia');
INSERT INTO countries (code, name) VALUES('LY', 'Libia');
INSERT INTO countries (code, name) VALUES('LI', 'Liechtenste');
INSERT INTO countries (code, name) VALUES('LT', 'Lituania');
INSERT INTO countries (code, name) VALUES('LU', 'Luxemburgo');
INSERT INTO countries (code, name) VALUES('MO', 'Macao');
INSERT INTO countries (code, name) VALUES('MK', 'ARY Macedonia');
INSERT INTO countries (code, name) VALUES('MG', 'Madagascar');
INSERT INTO countries (code, name) VALUES('MY', 'Malasia');
INSERT INTO countries (code, name) VALUES('MW', 'Malawi');
INSERT INTO countries (code, name) VALUES('MV', 'Maldivas');
INSERT INTO countries (code, name) VALUES('ML', 'Malí');
INSERT INTO countries (code, name) VALUES('MT', 'Malta');
INSERT INTO countries (code, name) VALUES('FK', 'Islas Malvinas');
INSERT INTO countries (code, name) VALUES('MP', 'Islas Marianas del Norte');
INSERT INTO countries (code, name) VALUES('MA', 'Marruecos');
INSERT INTO countries (code, name) VALUES('MH', 'Islas Marshall');
INSERT INTO countries (code, name) VALUES('MQ', 'Martinica');
INSERT INTO countries (code, name) VALUES('MU', 'Mauricio');
INSERT INTO countries (code, name) VALUES('MR', 'Mauritania');
INSERT INTO countries (code, name) VALUES('YT', 'Mayotte');
INSERT INTO countries (code, name) VALUES('MX', 'México');
INSERT INTO countries (code, name) VALUES('FM', 'Micronesia');
INSERT INTO countries (code, name) VALUES('MD', 'Moldavia');
INSERT INTO countries (code, name) VALUES('MC', 'Mónaco');
INSERT INTO countries (code, name) VALUES('MN', 'Mongolia');
INSERT INTO countries (code, name) VALUES('MS', 'Montserrat');
INSERT INTO countries (code, name) VALUES('MZ', 'Mozambique');
INSERT INTO countries (code, name) VALUES('MM', 'Myanmar');
INSERT INTO countries (code, name) VALUES('NA', 'Namibia');
INSERT INTO countries (code, name) VALUES('NR', 'Nauru');
INSERT INTO countries (code, name) VALUES('NP', 'Nepal');
INSERT INTO countries (code, name) VALUES('NI', 'Nicaragua');
INSERT INTO countries (code, name) VALUES('NE', 'Níger');
INSERT INTO countries (code, name) VALUES('NG', 'Nigeria');
INSERT INTO countries (code, name) VALUES('NU', 'Niue');
INSERT INTO countries (code, name) VALUES('NF', 'Isla Norfolk');
INSERT INTO countries (code, name) VALUES('NO', 'Noruega');
INSERT INTO countries (code, name) VALUES('NC', 'Nueva Caledonia');
INSERT INTO countries (code, name) VALUES('NZ', 'Nueva Zelanda');
INSERT INTO countries (code, name) VALUES('OM', 'Omán');
INSERT INTO countries (code, name) VALUES('NL', 'Países Bajos');
INSERT INTO countries (code, name) VALUES('PK', 'Pakistán');
INSERT INTO countries (code, name) VALUES('PW', 'Palau');
INSERT INTO countries (code, name) VALUES('PS', 'Palestina');
INSERT INTO countries (code, name) VALUES('PA', 'Panamá');
INSERT INTO countries (code, name) VALUES('PG', 'Papúa Nueva Guinea');
INSERT INTO countries (code, name) VALUES('PY', 'Paraguay');
INSERT INTO countries (code, name) VALUES('PE', 'Perú');
INSERT INTO countries (code, name) VALUES('PN', 'Islas Pitcairn');
INSERT INTO countries (code, name) VALUES('PF', 'Polinesia Francesa');
INSERT INTO countries (code, name) VALUES('PL', 'Polonia');
INSERT INTO countries (code, name) VALUES('PT', 'Portugal');
INSERT INTO countries (code, name) VALUES('PR', 'Puerto Rico');
INSERT INTO countries (code, name) VALUES('QA', 'Qatar');
INSERT INTO countries (code, name) VALUES('GB', 'Reino Unido');
INSERT INTO countries (code, name) VALUES('RE', 'Reunión');
INSERT INTO countries (code, name) VALUES('RW', 'Ruanda');
INSERT INTO countries (code, name) VALUES('RO', 'Rumania');
INSERT INTO countries (code, name) VALUES('RU', 'Rusia');
INSERT INTO countries (code, name) VALUES('EH', 'Sahara Occidental');
INSERT INTO countries (code, name) VALUES('SB', 'Islas Salomón');
INSERT INTO countries (code, name) VALUES('WS', 'Samoa');
INSERT INTO countries (code, name) VALUES('AS', 'Samoa Americana');
INSERT INTO countries (code, name) VALUES('KN', 'San Cristóbal y Nevis');
INSERT INTO countries (code, name) VALUES('SM', 'San Marino');
INSERT INTO countries (code, name) VALUES('PM', 'San Pedro y Miquelón');
INSERT INTO countries (code, name) VALUES('VC', 'San Vicente y las Granadinas');
INSERT INTO countries (code, name) VALUES('SH', 'Santa Helena');
INSERT INTO countries (code, name) VALUES('LC', 'Santa Lucía');
INSERT INTO countries (code, name) VALUES('ST', 'Santo Tomé y Príncipe');
INSERT INTO countries (code, name) VALUES('SN', 'Senegal');
INSERT INTO countries (code, name) VALUES('CS', 'Serbia y Montenegro');
INSERT INTO countries (code, name) VALUES('SC', 'Seychelles');
INSERT INTO countries (code, name) VALUES('SL', 'Sierra Leona');
INSERT INTO countries (code, name) VALUES('SG', 'Singapur');
INSERT INTO countries (code, name) VALUES('SY', 'Siria');
INSERT INTO countries (code, name) VALUES('SO', 'Somalia');
INSERT INTO countries (code, name) VALUES('LK', 'Sri Lanka');
INSERT INTO countries (code, name) VALUES('SZ', 'Suazilandia');
INSERT INTO countries (code, name) VALUES('ZA', 'Sudáfrica');
INSERT INTO countries (code, name) VALUES('SD', 'Sudán');
INSERT INTO countries (code, name) VALUES('SE', 'Suecia');
INSERT INTO countries (code, name) VALUES('CH', 'Suiza');
INSERT INTO countries (code, name) VALUES('SR', 'Surinam');
INSERT INTO countries (code, name) VALUES('SJ', 'Svalbard y Jan Mayen');
INSERT INTO countries (code, name) VALUES('TH', 'Tailandia');
INSERT INTO countries (code, name) VALUES('TW', 'Taiwán');
INSERT INTO countries (code, name) VALUES('TZ', 'Tanzania');
INSERT INTO countries (code, name) VALUES('TJ', 'Tayikistán');
INSERT INTO countries (code, name) VALUES('IO', 'Territorio Británico del Océano Índico');
INSERT INTO countries (code, name) VALUES('TF', 'Territorios Australes Franceses');
INSERT INTO countries (code, name) VALUES('TL', 'Timor Oriental');
INSERT INTO countries (code, name) VALUES('TG', 'Togo');
INSERT INTO countries (code, name) VALUES('TK', 'Tokelau');
INSERT INTO countries (code, name) VALUES('TO', 'Tonga');
INSERT INTO countries (code, name) VALUES('TT', 'Trinidad y Tobago');
INSERT INTO countries (code, name) VALUES('TN', 'Túnez');
INSERT INTO countries (code, name) VALUES('TC', 'Islas Turcas y Caicos');
INSERT INTO countries (code, name) VALUES('TM', 'Turkmenistán');
INSERT INTO countries (code, name) VALUES('TR', 'Turquía');
INSERT INTO countries (code, name) VALUES('TV', 'Tuvalu');
INSERT INTO countries (code, name) VALUES('UA', 'Ucrania');
INSERT INTO countries (code, name) VALUES('UG', 'Uganda');
INSERT INTO countries (code, name) VALUES('UY', 'Uruguay');
INSERT INTO countries (code, name) VALUES('UZ', 'Uzbekistán');
INSERT INTO countries (code, name) VALUES('VU', 'Vanuatu');
INSERT INTO countries (code, name) VALUES('VE', 'Venezuela');
INSERT INTO countries (code, name) VALUES('VN', 'Vietnam');
INSERT INTO countries (code, name) VALUES('VG', 'Islas Vírgenes Británicas');
INSERT INTO countries (code, name) VALUES('VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO countries (code, name) VALUES('WF', 'Wallis y Futuna');
INSERT INTO countries (code, name) VALUES('YE', 'Yemen');
INSERT INTO countries (code, name) VALUES('DJ', 'Yibuti');
INSERT INTO countries (code, name) VALUES('ZM', 'Zambia');
INSERT INTO countries (code, name) VALUES('ZW', 'Zimbabue');

# This is a clients data test
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Felipe', 'Jofré', 'felipe@test.test', NULL, 1, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Santiago', 'Fuentes', 'santiago@test.test', NULL, 2, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Lorena', 'Romero', 'lorena@test.test', NULL, 3, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('José', 'Maza', 'jose@test.test', NULL, 4, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Angélica', 'Jimenez', 'angelica@test.test', NULL, 5, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Rodrigo', 'Rodriguez', 'rodrigo@test.test', NULL, 6, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Fernanda', 'Rubilar', 'fernanda@test.test', NULL, 7, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Josefa', 'Cortez', 'josefa@test.test', NULL, 8, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('John', 'Cid', 'john@test.test', NULL, 9, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Gustavo', 'Doe', 'gustavo@test.test', NULL, 50, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Fabiola', 'Ramirez', 'fabiola@test.test', NULL, 11, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Ramón', 'Jara', 'ramon@test.test', NULL, 12, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Alejandro', 'Ocares', 'alejandro@test.test', NULL, 13, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Rosa', 'Lopez', 'rosa@test.test', NULL, 14, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Gabriela', 'Jimenez', 'gabriela@test.test', NULL, 15, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Ignacio', 'Poblete', 'ignacio@test.test', NULL, 16, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Karl', 'Lagos', 'karl@test.test', NULL, 17, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Oscar', 'Boric', 'oscar@test.test', NULL, 18, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Miriam', 'Bachelet', 'miriam@test.test', NULL, 19, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Camila', 'Romero', 'camilar@test.test', NULL, 20, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Luciano', 'Almeidas', 'luciano@test.test', NULL, 21, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Romualdo', 'Perez', 'romualdo.p@test.test', NULL, 22, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Karol', 'López', 'karol.l@test.test', NULL, 23, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Romina', 'Brito', 'romina.br@test.test', NULL, 24, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Miriam', 'Higuera', 'miriam.higuera@test.test', NULL, 25, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Alfred', 'Sandoval', 'alfred.sandoval@test.test', NULL, 26, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Rita', 'Rubilar', 'rita.rubilar1@test.test', NULL, 27, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Sandra', 'Ormeño', 'sandra.orm@test.test', NULL, 28, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Alberto', 'Polanco', 'alberto.p@test.test', NULL, 29, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Jimena', 'Urrutia', 'jimena.urr@test.test', NULL, 30, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Roberto', 'Moreno', 'roberto.m@test.test', NULL, 31, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Nilda', 'Fuentes', 'nilda.fuentes@test.test', NULL, 32, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Robin', 'Rubilar', 'rita.rubilar@test.test', NULL, 33, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Sultana', 'Troncoso', 'sultana@test.test', NULL, 34, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Ignacio', 'Quevedo', 'ignacio.que@test.test', NULL, 35, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Wilson', 'Dorán', 'wilson.doran@test.test', NULL, 36, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Humberto', 'Jara', 'humberto.jara@test.test', NULL, 37, NOW());
INSERT INTO clients (name, lastname, email, img_url, country_id, create_at) VALUES ('Alice', 'Bravo', 'alice.bravo@test.test', NULL, 38, NOW());